on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@V2
      - uses: r-lib/actions/setup-r@v1
      - name: Install package dependencies
        run: | 
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'install.packages("covr")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
      - run: Rscript build .
      - run: Rscript check *tar.gz --no-manual
      - run: Rscript -e 'covr::codecov()'
